### ISSUE TITLE
Q5A assignement number pads

### ISSUE THREAD

**Issue by Zaltora** [cpavlina/kicad-pcblib#4]
" kicad-pcblib/manuf.pretty/TEXAS-Q5A.kicad_mod"

Hi,
When i read the documentation CSD17501Q5A (N-Channel NexFET from TI) and compare with the package. I see that the pins are reversed.

**Comment by cpavlina** [comment]
Hm, my issue notification settings must be borked. This is old.

Anyway, looks fine to me - it's *rotated* vs the datasheet, not reversed, which is fine. I probably prepared it from a drawing that showed it the other way around.
